import "@radix-ui/themes/styles.css";

import type { Metadata } from "next";
import "./globals.css";
// import { Inter } from 'next/font/google';
import { Theme } from "@radix-ui/themes";
import NavBar from "./NavBar";

export const metadata: Metadata = {
  title: "Issue Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <NavBar />
          <main> {children} </main>
        </Theme>
      </body>
    </html>
  );
}
